"""UK Police Data API client."""

from ._client import AsyncPoliceAPI, PoliceAPI
from .exceptions import (
    PoliceAPIError,
    PoliceAPINotFoundError,
    PoliceAPIRateLimitError,
    PoliceAPIResponseError,
    PoliceAPIServerError,
    PoliceAPITimeoutError,
)
from .models import (
    AvailabilityDate,
    ContactDetails,
    Coordinates,
    Crime,
    CrimeCategory,
    CrimeLastUpdated,
    CrimeOutcome,
    CrimeWithOutcomes,
    EngagementMethod,
    Force,
    ForceLink,
    ForceOfficer,
    LocatedNeighbourhood,
    Location,
    Neighbourhood,
    NeighbourhoodEvent,
    NeighbourhoodLink,
    NeighbourhoodPriority,
    OutcomeCategory,
    OutcomeStatus,
    StopSearch,
    Street,
)
from .postcodes import AsyncPostcodesIO, GeocodedPostcode, PostcodesIO
from .utils import circle_polygon, encode_polygon, recent_months

__version__ = "0.1.0"

__all__ = [
    "PoliceAPI",
    "AsyncPoliceAPI",
    "PostcodesIO",
    "AsyncPostcodesIO",
    "GeocodedPostcode",
    "PoliceAPIError",
    "PoliceAPINotFoundError",
    "PoliceAPIRateLimitError",
    "PoliceAPIResponseError",
    "PoliceAPIServerError",
    "PoliceAPITimeoutError",
    "AvailabilityDate",
    "ContactDetails",
    "Coordinates",
    "Crime",
    "CrimeCategory",
    "CrimeLastUpdated",
    "CrimeOutcome",
    "CrimeWithOutcomes",
    "EngagementMethod",
    "Force",
    "ForceLink",
    "ForceOfficer",
    "Location",
    "LocatedNeighbourhood",
    "Neighbourhood",
    "NeighbourhoodEvent",
    "NeighbourhoodLink",
    "NeighbourhoodPriority",
    "OutcomeCategory",
    "OutcomeStatus",
    "StopSearch",
    "Street",
    "circle_polygon",
    "encode_polygon",
    "recent_months",
    "__version__",
]
